Repository WyriHaximus/github-action-helm3, pull requests merged in 2020-06, with the labels that each got.

#12 Add "git" for helm plugin installation support
  Dockerfile
Labels: enhancement

#13 Add optimized Docker based set up
  .dependabot/config.yml
  .github/CODEOWNERS
  .github/FUNDING.yml
  .github/boring-cyborg.yml
  .github/dependabot.yml
  .github/settings.yml
  .github/workflows/ci.yml
  .github/workflows/craft-release.yaml
  .github/workflows/set-milestone-on-pr.yaml
  Dockerfile
  Dockerfile-build
Labels: enhancement

#14 Test an array of helm commands
  .github/workflows/ci.yml
Labels: CI 🚧, Configuration ⚙, YAML 🍄

#15 Ensure action forwards output
  .github/workflows/ci.yml
  entrypoint.sh
Labels: CI 🚧, Configuration ⚙, Helm ☸, YAML 🍄

#16 Run helm install against KinD cluster
  .github/workflows/ci.yml
Labels: CI 🚧, Configuration ⚙, Docker 🐳, Helm ☸, YAML 🍄
